# Generated by Django 4.2.25 on 2025-10-21 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Anime',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roles_json', models.JSONField(default=list, help_text='Array of role names, e.g., ["CAPTAIN","VICE CAPTAIN","TANK","HEALER","SUPPORT","SUPPORT"]')),
                ('is_published', models.BooleanField(default=False, help_text='Only published templates appear on the play page')),
                ('specialty_match_multiplier', models.DecimalField(decimal_places=2, default=1.2, help_text='Multiplier applied when character specialty matches role', max_digits=4)),
                ('rating_bands_json', models.JSONField(default=dict, help_text='Percentile thresholds for draw ratings (S/A/B/C/D)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Template',
                'verbose_name_plural': 'Game Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('anime_power_scale', models.DecimalField(blank=True, decimal_places=2, help_text='Anime Power Scale (APS) - multiplier based on anime strength', max_digits=6, null=True)),
                ('character_power', models.DecimalField(blank=True, decimal_places=2, help_text='Character Power (CP) - must be between 1.00 and 100.00', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('specialty', models.CharField(blank=True, help_text='e.g., CAPTAIN, TANK, HEALER, SUPPORT', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='game.anime')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['name'],
            },
        ),
    ]
