# Generated by Django 4.2.25 on 2025-10-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='specialty',
        ),
        migrations.AddField(
            model_name='character',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='Array of specialties, e.g., ["CAPTAIN", "TANK"]'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
