# Generated by Django 4.2.25 on 2025-10-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_character_specialty_character_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametemplate',
            name='rating_bands_json',
            field=models.JSONField(blank=True, default=dict, help_text='Percentile thresholds for draw ratings (S/A/B/C/D). Leave empty to use defaults.'),
        ),
    ]
