# Generated by Django 4.2.25 on 2025-10-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gametemplate_rating_bands_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='anime_power_scale',
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_power_scale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Anime Power Scale (APS) - multiplier based on anime strength', max_digits=6, null=True),
        ),
    ]
