# Generated by Django 4.2.25 on 2025-10-25 19:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_remove_character_anime_power_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average user rating (0.00 - 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make this anime visible in public library (only for user-owned anime)'),
        ),
        migrations.AddField(
            model_name='anime',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this anime. Null = admin content (always public)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anime',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='Total number of ratings received'),
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this character. Null = admin content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this template. Null = admin content (always published)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnimeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating value (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(help_text='The anime being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='game.anime')),
                ('user', models.ForeignKey(help_text='User who submitted this rating', on_delete=django.db.models.deletion.CASCADE, related_name='anime_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anime Rating',
                'verbose_name_plural': 'Anime Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('anime', 'user')},
            },
        ),
    ]
