# Generated by Django 4.2.25 on 2025-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_anime_average_rating_anime_is_public_anime_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='original_creator_username',
            field=models.CharField(blank=True, help_text='Original creator username if this anime was imported from another user', max_length=255, null=True),
        ),
    ]
