# Generated by Django 4.2.25 on 2025-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_anime_original_creator_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
