# Generated by Django 4.2.25 on 2025-10-27 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('host_session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('guest_session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('host_nickname', models.CharField(default='Player 1', max_length=50)),
                ('guest_nickname', models.CharField(default='Player 2', max_length=50)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('anime_pool_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Player'), ('ready', 'Ready to Start'), ('in_progress', 'Game In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('host_connected', models.BooleanField(default=True)),
                ('guest_connected', models.BooleanField(default=False)),
                ('host_last_seen', models.DateTimeField(auto_now_add=True)),
                ('guest_last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('redis_state_key', models.CharField(blank=True, max_length=100, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_rooms', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('player_role', models.CharField(max_length=10)),
                ('action_data', models.JSONField()),
                ('sequence_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='multiplayer.multiplayerroom')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='multiplayerroom',
            index=models.Index(fields=['room_code'], name='multiplayer_room_co_8ac26f_idx'),
        ),
        migrations.AddIndex(
            model_name='multiplayerroom',
            index=models.Index(fields=['status'], name='multiplayer_status_2bc19e_idx'),
        ),
        migrations.AddIndex(
            model_name='multiplayerroom',
            index=models.Index(fields=['created_at'], name='multiplayer_created_d3903c_idx'),
        ),
        migrations.AddIndex(
            model_name='gameaction',
            index=models.Index(fields=['room', 'sequence_number'], name='multiplayer_room_id_3b1c51_idx'),
        ),
    ]
